// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1AtcCxmW8gOK3S0VSmgJpFhitxqK1MWM',
    appId: '1:511478810328:web:94d17fe93ad2ea93d2b9ad',
    messagingSenderId: '511478810328',
    projectId: 'restaurant-app-8d92d',
    authDomain: 'restaurant-app-8d92d.firebaseapp.com',
    storageBucket: 'restaurant-app-8d92d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4fYPs34zurgeb39SfscfgaKkN7e3Lucw',
    appId: '1:511478810328:android:e719d52a6dce2ab9d2b9ad',
    messagingSenderId: '511478810328',
    projectId: 'restaurant-app-8d92d',
    storageBucket: 'restaurant-app-8d92d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhdCowM1ZHPfy6etf1DT0pzx7iut5tc-4',
    appId: '1:511478810328:ios:3dfa5b7fc7568361d2b9ad',
    messagingSenderId: '511478810328',
    projectId: 'restaurant-app-8d92d',
    storageBucket: 'restaurant-app-8d92d.appspot.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhdCowM1ZHPfy6etf1DT0pzx7iut5tc-4',
    appId: '1:511478810328:ios:1345bcde92359d2fd2b9ad',
    messagingSenderId: '511478810328',
    projectId: 'restaurant-app-8d92d',
    storageBucket: 'restaurant-app-8d92d.appspot.com',
    iosBundleId: 'com.example.restaurantApp.RunnerTests',
  );
}
